datasets:
  dresscode_train:
    data_type: images
    dataroot_path: Null
    category: [ "dresses", "upper_body", "lower_body" ]
    size: [ 512, 384 ]
    clip_vit_path: openai/clip-vit-large-patch14
    offset: Null
    cloth_background_whitening: False
    cloth_mask_augmentation_ratio: 1.0