datasets:
  image_hms_train:
    fold: 5
    random_seed: 42
    data_type: images
    build_info:
      data_root:
        eeg: /home/work/hanxiao_train/input/hms/eeg_specs.npy
        spec: /home/work/hanxiao_train/input/hms/specs.npy
      ann_path: /home/work/hanxiao_train/HMS/train.csv