datasets:
  image_hms_eval:
    fold: 5
    random_seed: 42
    data_type: images
    build_info:
      data_root:
        eeg: /home/featurize/work/hms_dataset/eeg_specs.npy
        spec: /home/featurize/work/hms_dataset/specs.npy
      ann_path: /home/featurize/work/hms_dataset/train.csv