model:
  model_name: facebook/nllb-200-distilled-600M
  load_finetuned: False
  finetuned: ""
  arch: nllb_translator

  model_type: default

  lang_token_map:
    zh: "zho_Hans"
    ar: "arb_Arab"
    th: "tha_Thai"
    de: "deu_Latn"
    pl: "pol_Latn"
    fa: "pes_Arab"
    en: "eng_Latn"
    el: "ell_Grek"