model:
  model_name: /mnt/data/wangyesong01/models/Qwen2.5-VL-3B-Instruct
  arch: qwen2_5_vl_instruct
  model_type: default

  use_grad_checkpoint: False
  compute_type: bf16
  max_txt_len: 64
  max_output_txt_len: 1500
  q_lora_flag: True
  load_in_8bit: False

datasets:
  qwen_img2markdown_train:
    build_info:
      ann_path: /mnt/data/xuyang/datasets/DotA_dataset/train_zh.json
      media_dir: /mnt/data/xuyang/datasets/DotA_dataset
    vis_processor:
      train:
        name: "qwen_ocr_image_train"
        image_size:
          - 896
          - 672

  qwen_img2markdown_eval:
    build_info:
      ann_path: /mnt/data/xuyang/datasets/DotA_dataset/valid_zh.json
      media_dir: /mnt/data/xuyang/datasets/DotA_dataset

    vis_processor:
      eval:
        name: "qwen_ocr_image_eval"
        image_size:
          - 896
          - 672

run:
  runner: runner_iter_ds
  task: ds_zh_img2mkdown_train
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 2e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 2
  batch_size_eval: 2

  num_workers: 4
  warmup_steps: 1000

  iters_per_inner_epoch: 2000
  max_iters: 300000

  seed: 42
  output_dir: "/mnt/data/wangyesong/output/zh_img2markdown_qwen"
  save_opt_ckpt: False

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  only_save_best: True

  generate_cfg:
    do_sample: True
    num_beams: 5
    max_new_tokens: 256
    top_k: 20
    top_p: 0.8
    repetition_penalty: 1.05
    temperature: 0.7

  deepspeed_config:
    gradient_accumulation_steps: 4
    train_micro_batch_size_per_gpu: 2

    gradient_clipping: 1.
    steps_per_print: 128
    wall_clock_breakdown: False
    dump_state: False

    fp16:
      enabled: False
      loss_scale: 0
      loss_scale_window: 1000
      initial_scale_power: 16
      hysteresis: 2
      min_loss_scale: 1

    optimizer:
      type: "AdamW"
      params:
        lr: 1e-4
        betas: [ 0.9,0.99 ]
        eps: 1e-7
        weight_decay: 0.05

    bf16:
      enabled: True

    zero_optimization:
      stage: 2
      offload_optimizer:
        device: "cpu"
        pin_memory: True
      overlap_comm: True
      contiguous_gradients: True
      sub_group_size: 1e9
