model:
  model_name: Qwen/Qwen2.5-VL-7B-Instruct
  load_finetuned: False
  finetuned: ""
  load_pretrained: False
  pretrained: ""
  arch: qwen2_5_vl_instruct
  model_type: default

  use_grad_checkpoint: False
  compute_type: bf16
  max_txt_len: 128
  max_output_txt_len: 1500
