model:
  model_name: meta-llama/Llama-3.2-3B-Instruct
  load_finetuned: False
  finetuned: ""
  load_pretrained: False
  pretrained: ""
  arch: llama3_instruct

  model_type: default

  use_grad_checkpoint: False
  compute_type: bf16
  max_txt_len: 128
  max_output_txt_len: 256