model:
  arch: vq_vits
  model_type: default
  load_pretrained: True
  pretrained: ""
  load_finetuned: False
  finetuned: ""

  params:
    spec_channels: 1025  # filter_length // 2 + 1, filter_length = 2048
    segment_size: 32  # segment_size // hop_length, segment_size=20480, hp_length=640
    inter_channels: 192
    hidden_channels: 192
    filter_channels: 768
    n_heads: 2
    n_layers: 6
    kernel_size: 3
    p_dropout: 0.1
    resblock: "1"
    resblock_kernel_sizes: [ 3, 7, 11 ]
    resblock_dilation_sizes:
      - [ 1, 3, 5 ]
      - [ 1, 3, 5 ]
      - [ 1, 3, 5 ]
    upsample_rates: [ 10, 8, 2, 2, 2 ]
    upsample_initial_channel: 512
    upsample_kernel_sizes: [ 16, 16, 8, 2, 2 ]
    symbols_nums: 732
    gin_channels: 512
    use_sdp: True
    semantic_frame_rate: "25hz"
    freeze_quantizer: True
    use_spectral_norm: False
    text_low_lr_rate: 0.4
    mel_hps:
      hop_length: 640
      filter_length: 2048
      n_mel_channels: 128
      sampling_rate: 32000
      mel_fmin: 0.0
      mel_fmax: Null
      win_length: 2048
      c_mel: 45  # rec loss coefficient
      c_kl: 1.0  # kl loss coefficient




