# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
  arch: whisper
  model_type: medium
  language: japanese
  freeze_encoder: False

datasets:

  # whisper_common_voice_train:
  #   sample_ratio: 14118
  #   model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
  #   language: japanese
  #   data_root: /mnt/data/hanxiao/dataset/audio/common_voice_17_0-ja
  #   pre_normalize: True
  #   split:
  #     - train
  #     - validated

  whisper_fleurs_train:
    # sample_ratio: 2558
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    data_root: /mnt/data/hanxiao/dataset/audio/fleurs-ja
    language: ja
    split:
      - train
      - test


  whisper_fleurs_eval:
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    data_root: /mnt/data/hanxiao/dataset/audio/fleurs-ja
    language: ja
    split: test


run:
  runner: runner_iter
  task: whisper_asr_task
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-6
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 8
  batch_size_eval: 16
  accum_grad_iters: 8

  num_workers: 4
  warmup_steps: 256

  iters_per_inner_epoch: 256
  max_iters: 10240

  seed: 42
  output_dir: "./output/whisper_fleurs_new_ja"
  save_opt_ckpt: False

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]
  metric_key: cer

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True