# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
  arch: whisper
  model_type: medium
  language: tr
  freeze_encoder: False

datasets:
  # train
  whisper_common_voice_train:
    sample_ratio: 160461
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    language: tr
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/common_voice_17_0-tr
    split:
      - train
      - validated

  whisper_fleurs_train:
    sample_ratio: 2864
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-tr
    language: tr
    split: train

  whisper_greek_single_speaker_speech_train:
    sample_ratio: 2513
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/Open_SLR108_Turkish_10_hours
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    language: tr

  # eval
#  whisper_myaudio_eval:
#    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
#    language: fa

  whisper_fleurs_eval:
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-tr
    language: tr
    split: test


run:
  runner: runner_iter
  task: whisper_asr_task
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 8
  batch_size_eval: 16
  accum_grad_iters: 2

  num_workers: 4
  warmup_steps: 200

  iters_per_inner_epoch: 200
  max_iters: 10000

  seed: 42
  output_dir: "./output/whisper_v3_tr"
  save_opt_ckpt: False

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]
  metric_key: loss

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True