# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
  arch: whisper
  model_type: medium
  language: null
  freeze_encoder: False
  use_attention_mask: False

datasets:
  # train

  whisper_fleurs_train:
    sample_ratio: 1
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-en
    language: en
    augmentation: True
    split:
      - train
      - validation
      - test

  whisper_fleurs_train$copy1:
    sample_ratio: 1
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-de
    language: de
    augmentation: True
    split:
      - train
      - validation
      - test

  whisper_fleurs_train$copy2:
    sample_ratio: 1
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-nl
    language: nl
    augmentation: True
    split:
      - train
      - validation
      - test


  whisper_fleurs_concat_eval:
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-v3
    pre_normalize: False
    data_root:
      - /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-en
      - /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-de
      - /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-nl
    language:
      - en
      - de
      - nl
    split:
      - test
      - test
      - test

run:
  runner: runner_iter
  task: whisper_asr_task
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 2e-6
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 8
  batch_size_eval: 16
  accum_grad_iters: 8

  num_workers: 4
  warmup_steps: 200

  iters_per_inner_epoch: 200
  max_iters: 10000

  seed: 42
  output_dir: "./output/whisper_fleurs_en_de_nl"
  save_opt_ckpt: False

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]
  metric_key: wer

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True