# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  model_name: /mnt/data/hanxiao/models/audio/whisper-large-persian
  arch: whisper
  model_type: medium
  language: fa
  freeze_encoder: False

datasets:
  # train
  whisper_common_voice_train:
    sample_ratio: 1
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-persian
    language: fa

  whisper_common_voice_concat_train:
    sample_ratio: 1
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-persian
    language: fa

  whisper_common_voice_split_train:
    sample_ratio: 1
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-persian
    language: fa

  # eval
  whisper_myaudio_eval:
    model_name: /mnt/data/hanxiao/models/audio/whisper-large-persian
    language: fa


run:
  runner: runner_iter
  task: whisper_asr_task
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 8
  batch_size_eval: 16
  accum_grad_iters: 2

  num_workers: 4
  warmup_steps: 1000

  iters_per_inner_epoch: 1000
  max_iters: 30000

  seed: 42
  output_dir: "./output/whisper_asr_medium_fa_pro"
  save_opt_ckpt: False

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True