model:
  model_name: facebook/m2m100_1.2B
  load_finetuned: False
  finetuned: ""
  arch: opus_translator

  model_type: default
  max_length: 512
  source_lang: source_lang
  target_lang: target_lang
  source_spm: source_spm
  target_spm: target_spm
