model:
  model_name: Salesforce/SFR-Embedding-2_R
  load_finetuned: False
  finetuned: ""
  load_pretrained: False
  pretrained: ""
  arch: mistral_embedding

  model_type: default

  normalized: True
  sentence_pooling_method: 'last'
  negatives_cross_device: True
  temperature: 0.02
  use_inbatch_neg: True
  use_grad_checkpoint: False
  query_max_len: 256
  passage_max_len: 256