datasets:
  whisper_clip_fleurs_eval:
    data_type: audios
    language: el
    ann_path: Null
    clip_duration: 3.0
    data_root: /mnt/data/hanxiao/dataset/nlp/opus-zh-en/fleurs-el
    pre_normalize: False
    using_space_sep: True
    split: test