datasets:
  whisper_common_voice_split_train:
    data_type: audios
    language: fa
    musan_dir: null
    data_root: /mnt/data/hanxiao/dataset/audio/common-voice-17_0-persian
    split_nums: 2
    split:
      - train