model:
  load_finetuned: False
  finetuned: ""
  arch: vits
  model_type: default
  params:
    generator_model_name: generator_model_name
    discriminator_model_name: discriminator_model_name
    num_speakers: Null
    override_vocabulary_embeddings: False
    gradient_checkpointing: False
    weight_disc: 3.0
    weight_duration: 1.0
    weight_kl: 1.5
    weight_mel: 35.0
    weight_gen: 1.0
    weight_fmaps: 1.0