datasets:
  chatphone_train:
    data_type: images
    build_info:
      ann_path:
        - /home/work/hanxiao_train/input/chatphone/train_dataset_part-0.csv
        - /home/work/hanxiao_train/input/chatphone/train_dataset_part-1.csv
        - /home/work/hanxiao_train/input/chatphone/train_dataset_part-2.csv
        - /home/work/hanxiao_train/input/chatphone/train_dataset_part-3.csv
        - /home/work/hanxiao_train/input/chatphone/train_dataset_part-4.csv