datasets:
  viton_hd_eval:
    data_type: images
    build_info:
      data_root: /mnt/data/hanxiao/models/text2image/Viton-HD
      order: paired
      size:
        - 512
        - 384
      clip_vit_path: /mnt/data/hanxiao/models/autocv-cls/models/clip-vit-large-patch14