model:
  model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/vakyansh-wav2vec2-bengali-bnm-200
  load_finetuned: False
  finetuned: ""
  post_process_flag: True
  arch: bengali_harveen_wav2vec
  model_type: default
  freeze_encoder: False
  loss_reduction: "mean"
  processor_name: "/mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-xls-r-300m-bengali"
#  processor_name: arijitx/wav2vec2-xls-r-300m-bengali