model:
  arch: bert_classification
  model_type: default

  load_finetuned: False
  finetuned: ""

  model_name: google-bert/bert-base-multilingual-cased
  num_classes: 1
  dropout: 0.2
  freeze_encoder: False
