datasets:
  drug_mm_balanced_multi_class_eval:
    data_type: images
    label_map:
      sexual_drugs: 0
      addictive_drugs: 1
      medical_device: 2
      prescription_drugs: 3
      negative: 4
    build_info:
      ann_path: /home/work/hanxiao_train/input/drug/PH/data.json