datasets:
  drug_mm_binary_class_train:
    data_type: images
    num_classes: 1
    build_info:
      ann_path:
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part1.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part2.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part3.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part4.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part5.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part6.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part7.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part8.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part9.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part10.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part11.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part12.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part13.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part14.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part15.json
        - /home/work/hanxiao_train/input/drug/id_prohibited_classification_2024-03-01/id_prohibited_classification_2024-03-01-part16.json