datasets:
  vits_custum_train:
    data_type: audios
    model_name: model_name
    build_info:
      data_root: /mnt/data/hanxiao/models/audio/experiment/saspeech/saspeech_gold_standard/
      max_duration_in_seconds: 20.0
      min_duration_in_seconds: 0.0
      max_tokens_length: 450
      do_lower_case: False
      filter_on_speaker_id: Null
      do_normalize: False
      uroman_path: uroman_path
      language: Null