datasets:
  vits_train:
    data_type: audios
    model_name: model_name
    build_info:
      data_root: data_root
      audio_column_name: audio
      text_column_name: text
      max_duration_in_seconds: 20.0
      min_duration_in_seconds: 0.0
      max_tokens_length: 450
      do_lower_case: False
      speaker_id_column_name: speaker_id
      filter_on_speaker_id: Null
      do_normalize: False
      num_workers: 4
      uroman_path: uroman_path
      language: Null
      split:
        - train